### ISSUE TITLE
无法获取房间信息

### ISSUE THREAD

**Issue by dzxx36gyy** [Grayon/Douyu-for-Mac#23]
貌似今天突然就不行了，提示无法获取房间信息，是否是斗鱼换了api啥的？

**Comment by ddqp** [comment]
我的也是

**Comment by Grayon** [comment]
原来的api_key失效了，已经更新

**Comment by dzxx36gyy** [comment]
下午好像正常了一阵子，现在是房间是否开播正常，但是播放窗口会一闪而过(窗口消失，无法播放

**Comment by Grayon** [comment]
试试重启一下应用

**Comment by dzxx36gyy** [comment]
尝试重开应用(包括完全删除后更换内置mpv的版本，都不行，看surge记录发现http://hdl3.douyucdn.cn/live/ 这个直播流的url是请求了一次成功了就直接完成了，没有请求后续的flv分片

**Comment by Grayon** [comment]
这个就是视频流的地址，没有分片的。而且获取的链接只能使用一次。你出现的这种情况一般是主播虽然开播了，但是没有推流。或者视频流错误导致无法解析。但我这边测试播放都是正常的。

**Comment by dzxx36gyy** [comment]
我用surge抓到的地址浏览器访问下载的flv文件是有内容的，这就很奇怪……

**Comment by Grayon** [comment]
可以看到控制台的日志吗

**Comment by dzxx36gyy** [comment]
Surge控制台么，有请求
![](https://ws1.sinaimg.cn/large/65b34d7bgy1fmxzedy8ztj21em0yiwoi.jpg)

**Comment by Grayon** [comment]
[Douyu.app.zip](https://github.com/Grayon/Douyu-for-Mac/files/1593442/Douyu.app.zip)
试下这个，如果不行的话可以看下系统控制台的日志

**Comment by dzxx36gyy** [comment]
1.6(播放器一闪而过的)版本控制台日志如下
`默认	00:19:55.593075 +0800	Douyu	Unknown Window class (null) in Interface Builder file,
	 creating generic Window instead
默认	00:19:55.735095 +0800	kernel	[Douyu pid:22037 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 1 EG FBs 0:0 power-state 0 3D busy HDA idle
默认	00:19:58.099540 +0800	Douyu	Faulting in NSHTTPCookieStorage singleton
默认	00:19:58.099576 +0800	Douyu	Faulting in CFHTTPCookieStorage singleton
默认	00:19:58.099592 +0800	Douyu	Creating default cookie storage with process/bundle identifier
默认	00:19:58.103456 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.103764 +0800	Douyu	0x600000276dc0 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
默认	00:19:58.105088 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.105471 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.105611 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.105905 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.106121 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.106294 +0800	Douyu	0x60800027ff00 opened /Users/senra/Library/Keychains/login.keychain-db: 429872 bytes
默认	00:19:58.109907 +0800	Douyu	0x6180002731c0 opened /Library/Keychains/System.keychain: 39048 bytes
默认	00:19:58.113836 +0800	Douyu	TIC TCP Conn Start [1:0x6100001882d0]
默认	00:19:58.115452 +0800	Douyu	TIC TCP Conn Event [1:0x6100001882d0]: 1 Err(0)
默认	00:19:58.115477 +0800	Douyu	TIC TCP Conn Connected [1:0x6100001882d0]: Err(0)
默认	00:19:58.270524 +0800	Douyu	TIC Enabling TLS [1:0x6100001882d0]
默认	00:19:58.365680 +0800	Douyu	TIC TLS Event [1:0x6100001882d0]: 2, Pending(0)
默认	00:19:58.366592 +0800	Douyu	TIC TLS Event [1:0x6100001882d0]: 11, Pending(0)
默认	00:19:58.366870 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.367083 +0800	Douyu	UNIX error exception: 17
默认	00:19:58.367648 +0800	Douyu	TIC TLS Event [1:0x6100001882d0]: 12, Pending(0)
默认	00:19:58.367679 +0800	Douyu	TIC TLS Event [1:0x6100001882d0]: 14, Pending(0)
默认	00:19:58.393342 +0800	Douyu	TIC TLS Trust Result [1:0x6100001882d0]: 0
默认	00:19:58.462618 +0800	Douyu	TIC TLS Event [1:0x6100001882d0]: 20, Pending(0)
默认	00:19:58.463065 +0800	Douyu	TIC TCP Conn Event [1:0x6100001882d0]: 8 Err(0)
默认	00:19:58.463169 +0800	Douyu	TIC TLS Handshake Complete [1:0x6100001882d0]
默认	00:19:58.640948 +0800	kernel	[Douyu pid:22037 non-mux-aware] starting, non-mux-aware app count 1, switch-state 0 IG FBs 1 EG FBs 0:0 power-state 0 3D busy HDA idle
默认	00:19:58.778853 +0800	Douyu	[opengl-cb] fatal: glGetString(GL_VERSION) returned NULL.
默认	00:19:58.778949 +0800	Douyu	[opengl-cb] fatal: OpenGL not initialized.
默认	00:19:58.779392 +0800	Douyu	Stream client bypassing proxies on TCP Conn [2:0x608000188540]
默认	00:19:58.779431 +0800	Douyu	TCP Conn 0x608000188540 started
默认	00:19:58.781102 +0800	Douyu	TCP Conn 0x608000188540 event 1. err: 0
默认	00:19:58.781148 +0800	Douyu	TCP Conn 0x608000188540 complete. fd: 23, err: 0
默认	00:19:58.781638 +0800	Douyu	---认证服务器连接成功---
默认	00:19:58.906863 +0800	Douyu	---获得游客ID以及弹幕组---
默认	00:19:58.907017 +0800	Douyu	Stream client bypassing proxies on TCP Conn [3:0x6100001886e0]
默认	00:19:58.907040 +0800	Douyu	TCP Conn 0x6100001886e0 started
默认	00:19:58.907598 +0800	Douyu	TCP Conn 0x608000188540 canceled
默认	00:19:58.907632 +0800	Douyu	---认证服务器断开---
默认	00:19:58.909934 +0800	Douyu	TCP Conn 0x6100001886e0 event 1. err: 0
默认	00:19:58.909972 +0800	Douyu	TCP Conn 0x6100001886e0 complete. fd: 23, err: 0
默认	00:19:58.910166 +0800	Douyu	---弹幕服务器连接成功---
默认	00:19:59.527188 +0800	Douyu	[vo/opengl-cb] fatal: OpenGL context not initialized.
默认	00:19:59.527293 +0800	Douyu	[cplayer] fatal: Error opening/initializing the selected video_out (--vo) device.
默认	00:19:59.686505 +0800	Douyu	TCP Conn 0x6100001886e0 canceled
默认	00:19:59.686586 +0800	Douyu	----弹幕服务器断开----
默认	00:20:04.755226 +0800	kernel	[Douyu pid 22037 mux-aware] exiting, non-mux-aware app count 1, runtime: 0:00:09.020
默认	00:20:04.755726 +0800	kernel	[Douyu pid 22037 non-mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:06.115
`

你发的这个没问题，能够正常观看

**Comment by ddqp** [comment]
谢谢修复
