### ISSUE TITLE
有的房间号不是数字，解析不了

### ISSUE THREAD

**Issue by lancelock** [Grayon/Douyu-for-Mac#6]
比如 lol s7的直播间 http://www.douyu.com/t/s7
这个地址解析不了，要怎么解决呢？或者怎么查看它的真实id?

**Comment by dzxx36gyy** [comment]
浏览器开发者模式选中主播名，会有如下链接
`http://yuba.douyu.com/api/dy/anchor/anchorTopic?room_id=288016&uri=lols7`
使用该room_id即可，当然在直播列表内开发者模式选中直播间那块也有类似的room id

**Comment by Grayon** [comment]
输入lols7或288016都可以解析
