### ISSUE TITLE
如何控制清晰度？

### ISSUE THREAD

**Issue by TomatoFryEggs** [Grayon/Douyu-for-Mac#7]
RT

**Comment by Grayon** [comment]
目前的清晰度是超清，在PlayerViewController.m中，89行
#if 0 改成 #if 1 可以在有普清的直播间播放普清
函数中，播放URL可自行替换
self.roomInfo.videoUrl 是超清
self.roomInfo.middleVideoUrl 是高清
self.roomInfo.lowVideoUrl 是普清

**Comment by Grayon** [comment]
最新版支持选择默认清晰度
